### ISSUE TITLE
Where can I find the associated survey?

### ISSUE THREAD

**Issue by J-Vernay** [juj/RectangleBinPack#36]
Hello,
I want to redact a blog post on my implementation of skyline algorithm.
I wanted to refer to your excellent survey, however I did not find official links to it.
The only file I found was on FreeType-GL : https://github.com/rougier/freetype-gl/blob/master/doc/RectangleBinPack.pdf .
Is there an official location where the PDF can be found?
Have a nice day,

**Comment by juj** [comment]
The survey PDF is also in this repository: https://github.com/juj/RectangleBinPack/blob/master/RectangleBinPack.pdf

**Comment by J-Vernay** [comment]
My bad, thank you! :)

**Comment by J-Vernay** [comment]
@juj For your interest, the said blog post : https://jvernay.fr/en/blog/skyline-2d-packer/implementation/
Have a nice day!

**Comment by juj** [comment]
Very nice, the survey I did is starting to be quite old by now, so really great to see new material on the topic. 👍
